# SPDX-License-Identifier: GPL-2.0
generic-y += early_ioremap.h
generic-y += extable.h
generic-y += flat.h
generic-y += parport.h

generated-y += mach-types.h

syscall-y += syscall_table_eabi.h
syscall-y += syscall_table_oabi.h
