# SPDX-License-Identifier: GPL-2.0
# MIPS headers
syscall-y += syscall_table_n32.h
syscall-y += syscall_table_n64.h
syscall-y += syscall_table_o32.h

syscall-y += unistd_compat_n32.h
syscall-y += unistd_compat_o32.h

generic-y += kvm_para.h
generic-y += mcs_spinlock.h
generic-y += parport.h
generic-y += qrwlock.h
generic-y += qspinlock.h
generic-y += user.h
