# SPDX-License-Identifier: GPL-2.0


generated-y += orc_hash.h
generated-y += syscalls_32.h
generated-y += syscalls_64.h
generated-y += syscalls_x32.h
generated-y += unistd_compat_32.h
generated-y += unistd_compat_x32.h
generated-y += xen-hypercalls.h

generic-y += early_ioremap.h
generic-y += mcs_spinlock.h
