# SPDX-License-Identifier: GPL-2.0
generated-y += dis-defs.h
generated-y += facility-defs.h
syscall-y += syscall_table_64.h
syscall-y += syscall_table_32.h
syscall-y += unistd_compat_32.h

generic-y += asm-offsets.h
generic-y += kvm_types.h
generic-y += mcs_spinlock.h
